# Generated by Django 2.2 on 2021-03-01 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='CEP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=500)),
                ('student_name', models.CharField(max_length=200)),
                ('incharge', models.CharField(max_length=200)),
                ('coordinator', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('institute', models.CharField(blank=True, max_length=2000, null=True)),
                ('purpose', models.CharField(default='CEP', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.CharField(blank=True, max_length=300, null=True)),
                ('serial_no', models.CharField(max_length=50)),
                ('counter', models.IntegerField()),
                ('workshop', models.CharField(blank=True, max_length=1000, null=True)),
                ('paper', models.CharField(blank=True, max_length=1000, null=True)),
                ('verified', models.IntegerField(default=0)),
                ('serial_key', models.CharField(max_length=200, null=True)),
                ('short_key', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=25)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('purpose', models.CharField(default='SLC', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uin', models.CharField(max_length=50)),
                ('attendance', models.NullBooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('pin_number', models.CharField(max_length=10)),
                ('state', models.CharField(max_length=50)),
                ('purpose', models.CharField(default='SLC', max_length=10)),
                ('submitted', models.BooleanField(default=False)),
                ('answer', models.ManyToManyField(to='certificate.Answer')),
            ],
        ),
        migrations.AddField(
            model_name='answer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Question'),
        ),
    ]
